import type { LawCurriculumRow } from './lawCurriculumTypes';

/**
 * FSJPST: L1 and L2 are fully common; only L3 splits into Droit privé / Droit public.
 * (Source: programme PDF — deux années de tronc commun.)
 */
export const FSJPST_LAW_CURRICULUM: LawCurriculumRow[] = [
  // --- L1 Tronc commun — Semestre 1
  {
    key: 'l1-s1-droit-objectif',
    nameEn: 'Objective Law (Introduction to Law)',
    nameFr: 'Droit Objectif',
    level: 'L1',
    semester: 1,
    lawMajor: null,
  },
  {
    key: 'l1-s1-droit-constitutionnel-1-theorie',
    nameEn: 'Constitutional Law 1: General Theory',
    nameFr: 'Droit Constitutionnel 1 : Théorie Générale',
    level: 'L1',
    semester: 1,
    lawMajor: null,
  },
  {
    key: 'l1-s1-institutions-internationales',
    nameEn: 'International Institutions',
    nameFr: 'Institutions Internationales',
    level: 'L1',
    semester: 1,
    lawMajor: null,
  },
  {
    key: 'l1-s1-droits-homme',
    nameEn: 'Human Rights',
    nameFr: "Droits de l'Homme",
    level: 'L1',
    semester: 1,
    lawMajor: null,
  },
  {
    key: 'l1-s1-sociologie-politique',
    nameEn: 'Political Sociology',
    nameFr: 'Sociologie Politique',
    level: 'L1',
    semester: 1,
    lawMajor: null,
  },
  {
    key: 'l1-s1-droit-musulman',
    nameEn: 'Muslim Law',
    nameFr: 'Droit Musulman',
    level: 'L1',
    semester: 1,
    lawMajor: null,
  },
  {
    key: 'l1-s1-anglais-juridique',
    nameEn: 'Legal English',
    nameFr: 'Anglais Juridique',
    level: 'L1',
    semester: 1,
    lawMajor: null,
  },
  {
    key: 'l1-s1-c2i-informatique',
    nameEn: 'C2I / Computer Science',
    nameFr: 'C2I / Informatique',
    level: 'L1',
    semester: 1,
    lawMajor: null,
  },
  // --- L1 Tronc commun — Semestre 2
  {
    key: 'l1-s2-droit-constitutionnel-2-regimes',
    nameEn: 'Constitutional Law 2: Political Regimes and the Tunisian Regime',
    nameFr: 'Droit Constitutionnel 2 : Les Régimes Politiques et le Régime Tunisien',
    level: 'L1',
    semester: 2,
    lawMajor: null,
  },
  {
    key: 'l1-s2-droit-civil-theorie-generale',
    nameEn: 'Civil Law: General Theory of Subjective Rights',
    nameFr: 'Droit Civil : Théorie Générale du Droit Subjectif',
    level: 'L1',
    semester: 2,
    lawMajor: null,
  },
  {
    key: 'l1-s2-droit-civil-biens',
    nameEn: 'Civil Law: Property Law',
    nameFr: 'Droit Civil : Droit des Biens',
    level: 'L1',
    semester: 2,
    lawMajor: null,
  },
  {
    key: 'l1-s2-concurrence-droit-compare',
    nameEn: 'Competition Law / Comparative Law',
    nameFr: 'Droit de la Concurrence / Droit Comparé',
    level: 'L1',
    semester: 2,
    lawMajor: null,
  },
  {
    key: 'l1-s2-methodologie-juridique',
    nameEn: 'Legal Methodology',
    nameFr: 'Méthodologie Juridique',
    level: 'L1',
    semester: 2,
    lawMajor: null,
  },
  {
    key: 'l1-s2-anglais-juridique',
    nameEn: 'Legal English',
    nameFr: 'Anglais Juridique',
    level: 'L1',
    semester: 2,
    lawMajor: null,
  },
  {
    key: 'l1-s2-developpement-personnel',
    nameEn: 'Personal Development',
    nameFr: 'Développement Personnel',
    level: 'L1',
    semester: 2,
    lawMajor: null,
  },

  // --- L2 — Semestre 3 (common to Droit Privé and Droit Public)
  {
    key: 'l2-s3-tgo-contrats',
    nameEn: 'General theory of obligations: contracts',
    nameFr: 'Théorie Générale des Obligations : Les Contrats',
    level: 'L2',
    semester: 3,
    lawMajor: null,
  },
  {
    key: 'l2-s3-theorie-generale-droit-penal',
    nameEn: 'General theory of criminal law',
    nameFr: 'Théorie Générale du Droit Pénal',
    level: 'L2',
    semester: 3,
    lawMajor: null,
  },
  {
    key: 'l2-s3-organisation-administrative',
    nameEn: 'Administrative organization',
    nameFr: 'Organisation Administrative',
    level: 'L2',
    semester: 3,
    lawMajor: null,
  },
  {
    key: 'l2-s3-droit-assurances',
    nameEn: 'Insurance law',
    nameFr: 'Droit des Assurances',
    level: 'L2',
    semester: 3,
    lawMajor: null,
  },
  {
    key: 'l2-s3-culture-entreprise',
    nameEn: 'Business and corporate culture',
    nameFr: "Culture de l'Entreprise",
    level: 'L2',
    semester: 3,
    lawMajor: null,
  },
  {
    key: 'l2-s3-anglais-juridique',
    nameEn: 'Legal English',
    nameFr: 'Anglais Juridique',
    level: 'L2',
    semester: 3,
    lawMajor: null,
  },

  // --- L2 — Semestre 4 (six modules common to both tracks)
  {
    key: 'l2-s4-responsabilite-civile',
    nameEn: 'Civil liability',
    nameFr: 'La Responsabilité Civile',
    level: 'L2',
    semester: 4,
    lawMajor: null,
  },
  {
    key: 'l2-s4-droit-commercial',
    nameEn: 'Commercial law',
    nameFr: 'Droit Commercial',
    level: 'L2',
    semester: 4,
    lawMajor: null,
  },
  {
    key: 'l2-s4-action-administrative',
    nameEn: 'Administrative action',
    nameFr: 'Action Administrative',
    level: 'L2',
    semester: 4,
    lawMajor: null,
  },
  {
    key: 'l2-s4-succession',
    nameEn: 'Succession law',
    nameFr: 'Succession',
    level: 'L2',
    semester: 4,
    lawMajor: null,
  },
  {
    key: 'l2-s4-intro-fiscal-consommation',
    nameEn: 'Introduction to tax law / consumer law',
    nameFr: 'Introduction au Droit Fiscal / Droit de la Consommation',
    level: 'L2',
    semester: 4,
    lawMajor: null,
  },
  {
    key: 'l2-s4-anglais-juridique',
    nameEn: 'Legal English',
    nameFr: 'Anglais Juridique',
    level: 'L2',
    semester: 4,
    lawMajor: null,
  },
  {
    key: 'l2-s4-entreprenariat',
    nameEn: 'Entrepreneurship',
    nameFr: 'Entreprenariat',
    level: 'L2',
    semester: 4,
    lawMajor: null,
  },

  // --- L3 Droit Privé — Semestre 5
  {
    key: 'l3-dp-s5-procedures-civiles',
    nameEn: 'Civil procedure',
    nameFr: 'Procédures Civiles',
    level: 'L3',
    semester: 5,
    lawMajor: 'DROIT_PRIVE',
  },
  {
    key: 'l3-dp-s5-droit-societes-commerciales',
    nameEn: 'Commercial company law',
    nameFr: 'Droit des Sociétés Commerciales',
    level: 'L3',
    semester: 5,
    lawMajor: 'DROIT_PRIVE',
  },
  {
    key: 'l3-dp-s5-contrats-speciaux',
    nameEn: 'Special contracts',
    nameFr: 'Contrats Spéciaux',
    level: 'L3',
    semester: 5,
    lawMajor: 'DROIT_PRIVE',
  },
  {
    key: 'l3-dp-s5-droit-bancaire',
    nameEn: 'Banking law',
    nameFr: 'Droit Bancaire',
    level: 'L3',
    semester: 5,
    lawMajor: 'DROIT_PRIVE',
  },
  {
    key: 'l3-dp-s5-pi-voies-execution',
    nameEn: 'Intellectual property / enforcement procedures',
    nameFr: "Droit de la Propriété Intellectuelle / Voies d'Exécution",
    level: 'L3',
    semester: 5,
    lawMajor: 'DROIT_PRIVE',
  },
  {
    key: 'l3-dp-s5-anglais-juridique',
    nameEn: 'Legal English',
    nameFr: 'Anglais Juridique',
    level: 'L3',
    semester: 5,
    lawMajor: 'DROIT_PRIVE',
  },

  // --- L3 Droit Privé — Semestre 6
  {
    key: 'l3-dp-s6-droits-suretes',
    nameEn: 'Security rights and guarantees',
    nameFr: 'Droit des Sûretés',
    level: 'L3',
    semester: 6,
    lawMajor: 'DROIT_PRIVE',
  },
  {
    key: 'l3-dp-s6-droit-international-prive',
    nameEn: 'Private international law',
    nameFr: 'Droit International Privé',
    level: 'L3',
    semester: 6,
    lawMajor: 'DROIT_PRIVE',
  },
  {
    key: 'l3-dp-s6-procedures-penales',
    nameEn: 'Criminal procedure',
    nameFr: 'Procédures Pénales',
    level: 'L3',
    semester: 6,
    lawMajor: 'DROIT_PRIVE',
  },
  {
    key: 'l3-dp-s6-procedures-collectives',
    nameEn: 'Collective insolvency procedures',
    nameFr: 'Procédures Collectives',
    level: 'L3',
    semester: 6,
    lawMajor: 'DROIT_PRIVE',
  },
  {
    key: 'l3-dp-s6-histoire-idees-politiques',
    nameEn: 'History of political ideas',
    nameFr: 'Histoire des Idées Politiques',
    level: 'L3',
    semester: 6,
    lawMajor: 'DROIT_PRIVE',
  },
  {
    key: 'l3-dp-s6-effets-commerce',
    nameEn: 'Negotiable instruments and commercial paper',
    nameFr: 'Les Effets de Commerce',
    level: 'L3',
    semester: 6,
    lawMajor: 'DROIT_PRIVE',
  },

  // --- L3 Droit Public — Semestre 5
  {
    key: 'l3-dpu-s5-droit-international-public',
    nameEn: 'Public international law',
    nameFr: 'Droit International Public',
    level: 'L3',
    semester: 5,
    lawMajor: 'DROIT_PUBLIC',
  },
  {
    key: 'l3-dpu-s5-droit-fiscal',
    nameEn: 'Tax law',
    nameFr: 'Droit Fiscal',
    level: 'L3',
    semester: 5,
    lawMajor: 'DROIT_PUBLIC',
  },
  {
    key: 'l3-dpu-s5-droit-administratif-biens',
    nameEn: 'Administrative law of property',
    nameFr: 'Droit Administratif des Biens',
    level: 'L3',
    semester: 5,
    lawMajor: 'DROIT_PUBLIC',
  },
  {
    key: 'l3-dpu-s5-droit-nationalite',
    nameEn: 'Nationality law',
    nameFr: 'Droit de la Nationalité',
    level: 'L3',
    semester: 5,
    lawMajor: 'DROIT_PUBLIC',
  },
  {
    key: 'l3-dpu-s5-consommation-commerce-electronique',
    nameEn: 'Consumer law / e-commerce law',
    nameFr: 'Droit de la Consommation / Droit du Commerce Électronique',
    level: 'L3',
    semester: 5,
    lawMajor: 'DROIT_PUBLIC',
  },
  {
    key: 'l3-dpu-s5-anglais-juridique',
    nameEn: 'Legal English',
    nameFr: 'Anglais Juridique',
    level: 'L3',
    semester: 5,
    lawMajor: 'DROIT_PUBLIC',
  },

  // --- L3 Droit Public — Semestre 6
  {
    key: 'l3-dpu-s6-droit-public-economique',
    nameEn: 'Economic public law',
    nameFr: 'Droit Public Économique',
    level: 'L3',
    semester: 6,
    lawMajor: 'DROIT_PUBLIC',
  },
  {
    key: 'l3-dpu-s6-droit-fonction-publique',
    nameEn: 'Public service law',
    nameFr: 'Droit de la Fonction Publique',
    level: 'L3',
    semester: 6,
    lawMajor: 'DROIT_PUBLIC',
  },
  {
    key: 'l3-dpu-s6-contentieux-fiscal',
    nameEn: 'Tax litigation',
    nameFr: 'Contentieux Fiscal',
    level: 'L3',
    semester: 6,
    lawMajor: 'DROIT_PUBLIC',
  },
  {
    key: 'l3-dpu-s6-amenagement-pi',
    nameEn: 'Spatial planning law / intellectual property law',
    nameFr: "Droit de l'Aménagement du Territoire / Droit de la Propriété Intellectuelle",
    level: 'L3',
    semester: 6,
    lawMajor: 'DROIT_PUBLIC',
  },
  {
    key: 'l3-dpu-s6-histoire-idees-politiques',
    nameEn: 'History of political ideas',
    nameFr: 'Histoire des Idées Politiques',
    level: 'L3',
    semester: 6,
    lawMajor: 'DROIT_PUBLIC',
  },
  {
    key: 'l3-dpu-s6-anglais-juridique',
    nameEn: 'Legal English',
    nameFr: 'Anglais Juridique',
    level: 'L3',
    semester: 6,
    lawMajor: 'DROIT_PUBLIC',
  },
];
